require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
#$RNFirebaseAsStaticFramework = true

target 'rpsg1' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#    use_flipper!
#    post_install do |installer|
#      flipper_post_install(installer)
#    end
  
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  
end


